#see http://docs.spring.io/spring-boot/docs/1.4.4.RELEASE/reference/html/common-application-properties.html
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/testDB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: userone
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      properties:
        hibernate:
          show_sql: false
          format_sql: false
  #应用级别常量
  sys:
    rest:
      app-id: oR3YV1tti8
      app-secret: tuJM@)DirR9%1)ijp#
    session:
      domain: louchen.pub
      max-inactive-interval-in-seconds: 1800
    interceptor:
      sign: true
      auth: true
server:
  port: 8082