#see http://docs.spring.io/spring-boot/docs/1.4.4.RELEASE/reference/html/common-application-properties.html
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
  jpa:
      properties:
        hibernate:
          show_sql: false
          format_sql: false